version: "3"

services:
  traefik:
    image: traefik:2.1
    restart: unless-stopped
    command: traefik
    ports:
      - "80:80"
    environment:
      - DOMAIN_SUFFIX
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.port=8080"
      - "traefik.http.routers.api.service=api@internal"
      - "szg.url=http://traefik.szg.$DOMAIN_SUFFIX"

  nassau-https-proxy:
    build: ./nassau-https-proxy
    restart: unless-stopped
    ports:
     - "443:443"
    volumes:
     - ./nassau-https-proxy/data:/data
    labels:
     - "SERVICE_443_NAME=https"
     - "traefik.enable=false"

  ngrok:
    image: wernight/ngrok
    restart: unless-stopped
    command: start --config /etc/ngrok/ngrok.yml --all
    entrypoint: [ ngrok ]
    volumes:
      - ./ngrok:/etc/ngrok/

  ngrok-gen:
    image: mlebkowski/docker-gen
    restart: unless-stopped
    command: -config /etc/ngrok/docker-gen.conf
    volumes:
      - ./ngrok:/etc/ngrok
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - NGROK_AUTH
      - NGROK_HOSTNAME
      - NGROK_REGION
    labels:
      - "traefik.enabled=false"

  consul:
    image: consul:0.9.3
    restart: unless-stopped
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    expose:
      - "8301"
      - "8301/udp"
      - "8302"
      - "8302/udp"
    labels:
      - "traefik.http.services.consul-szg.loadbalancer.server.port=8500"
      - "SERVICE_53_IGNORE=true"
      - "SERVICE_8500_NAME=ui.consul"
      - "SERVICE_8300_IGNORE=true"
      - "SERVICE_8301_IGNORE=true"
      - "SERVICE_8302_IGNORE=true"
      - "SERVICE_8400_IGNORE=true"

  dnsmasq:
    image: andyshinn/dnsmasq
    restart: unless-stopped
    command: --log-facility=- --log-queries --address=/$DOMAIN_SUFFIX/127.0.0.1 
    ports:
     - "53:53"
     - "53:53/udp"
    labels:
     - "SERVICE_53_NAME=dns"
     - "traefik.enable=false"
    cap_add:
      - NET_ADMIN

  registrator:
    image: gliderlabs/registrator:latest
    command: -internal consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    links:
      - consul

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 8025
      - 1025:1025
    labels:
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
      - "SERVICE_1025_NAME=smtp"
      - "SERVICE_8025_NAME=mailhog"

  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    labels:
      - "traefik.port=9000"

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
     - "3306:3306"
    volumes:
     - mysql:/var/lib/mysql
     - ./mysql:/etc/mysql/conf.d
    labels:
     - "traefik.enable=false"
    environment:
     - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

  redis:
    image: redis
    restart: unless-stopped
    ports:
     - "6379:6379"
    command: --appendonly yes
    volumes:
     - redis:/data
    labels:
     - "traefik.enable=false"
   
  elasticsearch:
    image: elasticsearch:1
    restart: unless-stopped
    ports:
     - "9200:9200"
    labels:
     - "traefik.port=9200"
     - "SERVICE_9200_NAME=elasticsearch"
     - "SERVICE_9300_IGNORE=true"
    volumes:
     - elasticsearch:/usr/share/elasticsearch/data

volumes:
  portainer:
  mysql: 
  elasticsearch:
  redis:
  composer:
  npm:
